#!/bin/bash
#!/bin/bash

# list files in current directory in long format
ls -al

# list files in parent directory in long format
ls -al ../

# list files in /boot directory in long format
ls -al /boot/
